name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - bugfix/**
      - feature/**
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: maven
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: npm
        cache-dependency-path: 'src/main/webapp/package-lock.json'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
